cajal/pipeline

matlab/scripts/prepare_madmax.m, matlab/scripts/prepare_monet.m
The Monet and MadMax movies along with data are retrieved in 
`./matlab/scripts/prepare_monet.m`
`./matlab/scripts/prepare_madmax.m`
=> Fixed collaborator data retrieval scripts.

python/pipeline/experiment.py
=> migrated rf.Stack to experiment.Stack (issue #100)

matlab/schemas/+preprocess/BehaviorSync.m, matlab/schemas/+preprocess/Eye.m, matlab/schemas/+preprocess/EyeQuality.m, matlab/schemas/+preprocess/EyeTracking.m, matlab/schemas/+preprocess/EyeTrackingFrame.m, matlab/schemas/+preprocess/TrackingParameters.m
Added Matlab classes for eye, bugfix BehaviorSync
=> Added Matlab classes for eye, bugfix BehaviorSync

matlab/schemas/+experiment/TreadmillSpecs.m, matlab/schemas/+preprocess/Treadmill.m
Load treadmill velocity and timestamps from behavior file (issue #95)
=> Added preprocess.Treadmill

matlab/schemas/+experiment/Rig.m, matlab/scripts/pupil_and_trace.m
Example showing how to fetch and plot pupil x,y, and radius, synchronized with calcium data and visual stimulus info.
=> Example script for pupil, trace, vis stim on same clock

matlab/schemas/+vis/MonetLookup.m, matlab/schemas/+vis/Movie.m, matlab/schemas/+vis/Trippy.m, python/pipeline/preprocess.py, python/pipeline/settings.py, python/pipeline/tuning.py, python/pipeline/vis.py
also added tuning.RF but not completed yet.
=> Updated visual stimuli to use the vis schema instead of psy

matlab/schemas/+experiment/Stack.m, matlab/schemas/+stack/SliceAlignment.m, matlab/schemas/+stack/StackInfo.m, matlab/schemas/+stack/StackMotion.m, matlab/schemas/+stack/correctedStackMovie.m, matlab/schemas/+stack/correctedStackTiff.m, matlab/schemas/+stack/getSchema.m, matlab/schemas/+stack/getStackReader.m, matlab/schemas/+stack/loadCorrectedStack.m
stack.SliceAlignment is copied with minor changes from previous schema.
=> stack schema, stack motion correction, and export fcns

matlab/schemas/+preprocess/ManualSegment.m
Overloaded delete function enforces delete of dependent data before delete of manual segmentation
=> Added overloaded delete function for preprocess.ManualSegment

Dockerfile, python/pipeline/preprocess.py, python/pipeline/utils/eye_tracking.py, python/scripts/worker-populate.py
* fixed `**key, ratetrace=...` order bug (that's python 3.5 syntax, but we also want to use python 3.4)
* added new features to tracker
* added new features to populate script
* deleted line from dockerfile
=> eye tracking, bugfix, population script update, dockerfile

matlab/schemas/+vis/ScanConditions.m
Table linking visual conditions with scan_idx
=> ScanConditions table

matlab/schemas/+preprocess/PrepareGalvo.m
Fixed a bug + accounted for multiple aspect ratios
=> Correct FoV calculation

matlab/schemas/+preprocess/ExtractRaw.m, matlab/schemas/+preprocess/ManualSegment.m
Manual segmentation is using paintMasks function from commons library. 
Manual segmentation has a mask image with unique mask numbers.
=> Masks carry unique cell information and are created with paintMasks

Dockerfile, python/pipeline/__init__.py, python/pipeline/preprocess.py, python/pipeline/utils/galvo_corrections.py, python/tests/test_preprocess.py
Copied the version from Matlab (commons.ne7.ip.correctRaster) and checked against it.
=> The raster correction function and tests

matlab/schemas/+stimulus/+conf/Grate.m, matlab/schemas/+stimulus/+conf/Grating.m, matlab/schemas/+stimulus/+conf/matisse.m, matlab/schemas/+stimulus/+conf/matisse2.m, matlab/schemas/+stimulus/+conf/monet2.m, matlab/schemas/+stimulus/Grate.m, matlab/schemas/+stimulus/Grating.m, matlab/schemas/+stimulus/Matisse.m, matlab/schemas/+stimulus/Matisse2.m, matlab/schemas/+stimulus/Monet.m, matlab/schemas/+stimulus/Monet2.m, matlab/schemas/+stimulus/TempKernel.m
* `stimulus.Matisse2` -- translational motion of static noise with controlled coherence and aperture
* `stimulus.Monet2` -- Gaussian noise with periods of coherence motion
* `stimulus.Grate` -- simple oriented grating
* `stimulus.Monet`  -- migrated data from the +vis schema.
=> implemented stimulus.Matisse2 and stimulus.Monet2

matlab/schemas/+stimulus/+conf/Varma.m, matlab/schemas/+stimulus/+conf/VarmaTest.m
Two config files for Varma:
VarmaTest (11 mins)
and
Varma (110 mins )
=> Created separate config file VarmaTest

matlab/schemas/+experiment/Scan.m, matlab/schemas/+preprocess/Sync.m, matlab/schemas/+stimulus/+core/Control.m, matlab/schemas/+stimulus/Clip.m, matlab/schemas/+stimulus/Sync.m, python/pipeline/preprocess.py, python/pipeline/stimulus.py, python/pipeline/tuning.py
* added pipeline/stimulus  (python)
* added `stimulus.Sync` (Matlab), including its migration script
* added migration script in `stimulus.Clip` (Matlab)
=> added the stimulus schema in Python and stimulus.Sync in maltab

Dockerfile, python/pipeline/preprocess.py, python/pipeline/utils/caiman_interface.py, python/pipeline/utils/galvo_corrections.py
Subpixel motion correction works fine and is not really inefficient because it is multi-threaded. GalvoAverage Frame as done in Matlab.
=> Subpixel motion correction (via skimage.register_transform) and GalvoAverageFrame

python/pipeline/utils/galvo_corrections.py
Clean version of motion correction, I ended up copying the code from skimage (to avoid the overhead). Works fine.
=> Deleting some of the code for testing motion corrections, sticking with register_translation

Dockerfile, python/pipeline/meso.py, python/pipeline/reso.py
Dockerfile had comments so some lines weren't executing. And added decreasing edges of template to zero to avoid artifacts, results are pretty similar. Reso and meso data was already updated (only 8 scans changed in reso, and one in meso)
=> Fix dockerfile and taper edges of template in raster correction

python/pipeline/experiment.py, python/pipeline/meso.py, python/pipeline/notify.py, python/pipeline/reso.py, python/pipeline/shared.py, python/pipeline/utils/caiman_interface.py, python/pipeline/utils/signal.py
Also defined new experiment.Stack (no pipeline code yet)
=> Added nmf per patches as segmentation_method=3

Dockerfiles/Dockerfile.base, python/pipeline/experiment.py, python/pipeline/meso.py, python/pipeline/reso.py, python/pipeline/shared.py
Also, settings for some simple bouton segmentation using nmf
=> Renaming slice to field and reso/meso_version to pipe_version in preparation for merging

Dockerfiles/Dockerfile.base, python/pipeline/meso.py, python/pipeline/reso.py, python/pipeline/utils/caiman_interface.py, python/pipeline/utils/quality.py
Updated caiman and the function calls in caiman_interface; using multiprocessing for caiman rather than ipcluster; fix little bug in Quality; save traces as np.float32 and parallelize activity deconvolution
=> Fixing HubConnectionError and some other fixes

python/pipeline/meso.py, python/pipeline/reso.py, python/pipeline/stack.py, python/pipeline/utils/galvo_corrections.py, python/pipeline/utils/performance.py, python/pipeline/utils/stitching.py
and some name attribute changes in MotionCorrection table
=> No smoothing of motion shifts

python/pipeline/meso.py, python/pipeline/reso.py, python/pipeline/stack.py, python/pipeline/utils/performance.py, python/pipeline/utils/stitching.py
Generate the initial template for motion correction by computing the correlation between frames, selecting the frame that has the highest mean correlation with all others frames (to get a frame with good signal in it) and averaging the 10 frames that correlate highly with the selected frame. Before I just selected the middle one but that frame could be entirely dark or too noisy
=> small improvement in stack motion correction

jupyter/Dockerfile, python/pipeline/fastmeso.py, python/pipeline/meso.py, python/pipeline/reso.py, python/pipeline/stack.py, python/pipeline/utils/performance.py, python/pipeline/utils/registration.py, python/pipeline/utils/stitching.py, python/scripts/populate-minion.py
Process thing in AutoProcessing even if they're in ScanIgnored and make y point downwards for stitching.
=> Some minor changes

Dockerfiles/Dockerfile.base, matlab/scripts/populate_sync.m, python/pipeline/stack.py, python/pipeline/utils/h5.py, python/pipeline/utils/stitching.py, python/scripts/populate-minion.py
- Fix bug in size of FieldInStack during registration.
- Add StackSet to create unique ids per stack
- Reorder populate script
- Allow stitching with a min of 10 pixels / before min was half width of smaller field
=> Set of small improvements

python/pipeline/posture.py
New table stores posture camera total number of frames and 16 preview frames.
=> add table for posture camera preview

python/pipeline/experiment.py, python/pipeline/posture.py, python/pipeline/pupil.py, python/pipeline/treadmill.py, python/pipeline/utils/__init__.py, python/pipeline/utils/h5.py, python/scripts/populate-minion.py
Minor fixes and dealing with possible errors in timestamps
=> Reformat treadmill, pupil, posture

matlab/schemas/+vis/MonetLookup.m
This table def was on 2p4 and was uncommited until now.
=> added MonetLookup to matlab schemas +vis

python/pipeline/shared.py, python/pipeline/stack.py
Added two new tables and paraboloid fit to determine surface of brain in stack.
=> Added surface calculation method and table

python/pipeline/pupil.py, python/scripts/populate-minion.py, python/scripts/populate-minion_gpu.py
updates include:
1. pupil.Tracking now in minion-gpu script and restricted by date, 2019-01-01
2. pupil.FittedPupil now in minion script
3. tune_scans is restricted by date, 2019-01-01
=> pupil now fully integrated into minion script

python/pipeline/pupil.py
1. delete short dir and compressed/cropped vid
2. transfer from old manual tracking table to new manual tracking table
=> updates on pupil tracking 

Dockerfile, Dockerfile.base, python/pipeline/pupil.py, python/pipeline/utils/DLC_tools.py, python/pipeline/utils/eye_tracking.py
1. delete short video directory and compressed/cropped video
2. when fitting refer to the original video, then use cropping coordinates to appropriately crop the original video
3. add gpu number argument in prediction function
=> Updating pupil package

python/pipeline/shared.py
Fixed error where SurfaceMethod did not contain decorator
=> Added schema decoration to SurfaceMethod

python/pipeline/pupil.py
=> update function name

matlab/schemas/+meso/SegmentationManual.m, python/pipeline/odor.py, python/pipeline/utils/h5.py
Adds a new odor.py file for olfaction pipeline, updates h5.py with related functions, and fixes meso SegmentationManual.m being empty.
=> Adding odor pipeline schema

python/pipeline/reso.py
This is a fix for voltage imaging done through reso.
=> Added motion correct passthrough for high FPS

python/pipeline/injection.py, python/pipeline/meso.py, python/pipeline/reso.py, python/pipeline/shared.py
- FieldAnnotation added to meso.py & reso.py
- shared.py updated to include FieldAnnotation lookup (ExpressionConstruct)
- injection.py schema added
=> Add FieldAnnotation table and Injection schema

python/pipeline/pupil.py
Creation of FittedPupil.EyePoints table that saves the 16 eye points tracked and saved by Deeplabcut
=> Eye points

python/pipeline/shared.py
Fixes bug in _make_hamming_window() which failed to convert float to int for a length variable
=> FilterMethod bug fix

.gitignore, python/pipeline/pupil.py, python/pipeline/treadmill.py, python/pipeline/utils/clocktools.py
Adds missing comments, adds missing PipelineException import, and remove redundant imports in pupil.py
=> Improve documentation and imports

matlab/schemas/+map/UnitRet.m, matlab/schemas/+map/UnitRetParam.m
Implement UnitRet table and UnitRetParam table to allow unit retinotopy to be calculated with multiple parameter sets.
=> Unit retinotopy with Gaussian smoothing

python/pipeline/shared.py, python/pipeline/stack.py, python/pipeline/utils/h5.py
* added increased kernel width to remove ambiguity in "unknown" area classifications for units
* added methods in AreaMethod to represent changes
=> Area membership

python/pipeline/shared.py
Converted window_idx_length to int type.
=> Bugfix shared.FilterMethod median filter

python/pipeline/pupil.py
Fixed indentation error in pupil.py
=> Indent bugfix

python/pipeline/odor.py
Added error checking if irregular frame times are detected. Code attempts to find longest fragment and fix the error automatically, if possible.
=> Added OdorSync fix for odd scans

python/pipeline/treadmill.py
Added running_method_id (4,5,6) and added clocktools import for get_running_idx() and get_nonrunning_idx()
=> Add new treadmill.Running method

python/pipeline/stack.py, python/pipeline/utils/performance.py
Correlation Stack population methods to mirror CorrectedStack population approach and utilties
add performance.parallel_correlate_stack as the parallel compute utility called by CorrelationStack populate
=> CorrelationStack 

python/pipeline/utils/clocktools.py
Found a critical bug that caused errors when fetching timing/interpolation data for "fluorescence-*" or "deconvolution-*" settings.
When including a `unit_id` or `mask_id` in the key for convert_clocks, the internal function `fetch_timing_data` would pull from the ms_delay stored in `pipe.ScanSet.UnitInfo` and add it to the current timestamps. However, timestamps are stored in seconds while `ms_delay` was converted to milliseconds. `ms_delay` was previously not divided by 1,000 before being added to the current timestamps, leading to reported times that can be 1s - 20s off. This would also make units that are fairly synchronized appear completely uncorrelated.
When including just `field` in the key for convert_clocks, the field delay was calculated from the delay image stored in …
=> Fixing critical timing bug in clocktools
