cajal/pipeline

python/pipeline/__init__.py
python/pipeline/preprocess.py
python/scripts/worker-populate.py

- When the key_source of a computed relation was not properly defined, populate would do nothing but progress would still show that the relation is not fully populated. Because of that, the worker constantly tried to populate the remaining items, jamming the server. I added a time condition to account for that. 
- `preprocess.ComputeTraces`  had exactly that problem. Sometimes there were just no traces for a particular scan. I fixed that in the `key_source`.

bugfix in population worker and key_source of ComputeTraces

---

matlab/schemas/+preprocess/PrepareGalvo.m

- ratio was the wrong way around. If zoom=1 and the closest zoom is 1.1, then the scaling for the FOV should be 1.1/1 not 1/1.1.

bugfix in PrepareGalvo

---

python/pipeline/preprocess.py
python/pipeline/pupil.py
python/pipeline/utils/eye_tracking.py

- fix one bug that didn't allow the eyetracking to be run in a docker container 
- cleanup imports so tiffreader and caiman do not *need* to be installed unless you need them

pupil tracker update and import cleanup

---

python/pipeline/__init__.py
python/pipeline/behavior.py
python/pipeline/experiment.py
python/pipeline/maps.py
python/pipeline/meso.py
python/pipeline/notify.py
python/pipeline/pupil.py
python/pipeline/quality.py
python/pipeline/reso.py
python/pipeline/shared.py
python/pipeline/tuning.py
python/pipeline/utils/caiman_interface.py
python/pipeline/utils/eye_tracking.py

Steps are pretty similar to those in reso, except that some information has been added (such as height width, um_x, um_y and rois per field) some other deleted (such as zoom) and each mask has a delay in milliseconds from the start of the frame (in ScanSet.UnitInfo). In theory they could now keep diverging as we add more scan-specific steps (for instance if we want to do some tiling in mesoscope).
Here are the steps:
```python
from pipeline import meso
key = {'animal_id': 14445, 'session': 3, 'scan_idx': 3}
meso.ScanInfo().populate(key) # read header info, compute quantal size and compute delays per field
meso.CorrectionChannel().insert1({**key, 'field': 1, 'channel': 1})
meso.CorrectionChannel().insert1({**key, 'field': 2, 'channel': 1})
meso.CorrectionChannel().insert1({**key, 'field': …
```

Meso pipeline

---

python/pipeline/meso.py
python/pipeline/reso.py

Processed scans have already been fixed, but use this version to process new things (otherwise zs may be wrong)

Fix bug of using zstepsize when calculating slice's depth

---

python/pipeline/meso.py
python/pipeline/reso.py
python/pipeline/shared.py

Classes that can process pipeline outputs (masks, traces, spikes, info) per slice can depend on Activity (key is scan, slice, channel), classes that need to process the scan as an atomic object can depend on ScanDone (key is scan), which takes cares of keeping itself updated. This way processing in the pipeline can be done per slice but results in further steps could be processed per slice as they come or per scan in a bundle.
Also, changed dependency of ScanSet from Segmentation to Fluorescence (it should have been like that but I didn't notice before)

Added ScanDone at end of reso/meso for scan-level processing

---

Dockerfile
Dockerfiles/Dockerfile.base
Dockerfiles/Dockerfile.portainer
fabfile.py
python/pipeline/maps.py
python/pipeline/meso.py
python/pipeline/reso.py

- I split the lengthy build part of the docker file into a separate one. That needs to be built less frequent and we can do that locally here. With the split, we can get automatic builds on Dockerhub back. 
- To build it locally, I built a fabfile. After installing `fabric3` one can compile the entire pipeline with `fab -H COMPUTERNAME build_base:1,1,'cajal' build_latest:1,0,'cajal'`. There are also recipes to push the images. 
- I also renamed the attribute names in the part tables for summary images. Before they all were names `image` which is annoying when joining the part tables. I already moved the underlying database.

Split Dockerfile, add fabfile, rename summary image attributes

---

python/pipeline/meso.py
python/pipeline/notify.py
python/pipeline/reso.py
python/pipeline/utils/signal.py

It computes four metrics (for each slice and channel combination): quantal size (moved from ScanInfo), mean intensity over time, mean contrast over time (99th - 1th percentile), and scan summaries (16 mean images through time: mean over chunks of time).

Adding some quality metrics for raw scans (reso/meso.Quality)

---

Dockerfiles/Dockerfile.base
python/pipeline/meso.py
python/pipeline/reso.py
python/pipeline/shared.py
python/pipeline/utils/caiman_interface.py
python/pipeline/utils/galvo_corrections.py
python/pipeline/utils/signal.py

Add automatic mask classfiication using CaImAn's convnet and also modify Segmentation to work with latest version of caiman (no online yet, though).
In motion correction, use linear rather than cubic interpolation (faster and very similar results), fill in out-of-bounds values with zero rather than extrapolate and center motion shifts using the median rather than the mean to decrease outlier/black frame leverage.
Also drop type from ScanSet.UnitInfo. Now, unit types will only be in MaskClassification.Type

Mask Classification and some improvements to MotionCorrection

---

python/pipeline/treadmill.py
python/pipeline/utils/h5.py

Change threshold to consider a packet mistamped from 30 msecs to 20 msecs
Fix checking whether last position in the frame times is NaN
When setting velocity to NaN in treadmill, set their respective timepoints to NaN, too

Bug fixes in treadmill

---

python/pipeline/odor.py

The columns 'trace' and 'times' in odor.Respiration contain data with upwards of 1mil data points. The variable type has been changed from longblob to external to lessen stress on the database. SQL tables have already been updated to reflect this.

odor.Respiration table changed to external

---

python/pipeline/odor.py

Due to issues with collaborators, temporarily switching odor.Respiration to use longblobs instead of externals.

Convert external-odor to longblob

---

Dockerfile.base

The original command `pip3 install --upgrade datajoint~=0.11` will update datajoint to 0.12.x

fix datajoint version to 0.11.x

---

python/pipeline/pupil.py
python/pipeline/treadmill.py
python/pipeline/utils/clocktools.py

Three major changes:
1. New file in pipeline.utils called clocktools.py
- Adds auto-conversion functions between any clocks (behavior, stimulus, odor)
- Adds auto-interpolation and fetching of signals for nearly all signals of interest (fluorescence, deconvolved activity, respiration, treadmill, pupil)
- Takes as input indices or time boundaries on any clock
2. New tables to pupil.py
- ProcessedPupil auto-filters pupil radii
- Other tables store all detected dilation/constriction events or define methods to do so
3. New tables to treadmill.py
- Running table detects bouts of running and stores each event
- RunningMethod stores different methods to detect running like threshold + max gap between the same running bout

Add clocktools, pupil processing, treadmill processing

---

python/pipeline/utils/clocktools.py

Treadmill and odor now use clocktools at specific points. Changing import to virtual module to prevent recursive import calls.

Fix clocktools to prevent recursive import

---

python/pipeline/pupil.py
python/pipeline/treadmill.py

Clocktools was previously imported in the beginning of treadmill.py and pupil.py. However, clocktools requires stimulus.py, adding an unnecessary dependency for everything. The import was moved to the specific functions which require it.

Fix clocktools import to prevent extra dependencies

---

python/pipeline/shared.py
python/pipeline/treadmill.py
python/pipeline/utils/clocktools.py

The following changes were made:
1. Adding two new running methods to treadmill which can now pad running periods with a specific amount of time.
* running_method_id 2 pads with 1sec with a lower threshold of 0.5cm/sec, while running_method_id 3 pads with 10sec with 0.5cm/sec threshold
* Running periods with padding cannot extend past the first/last recording time for the treadmill trace
2. Clocktools no longer imports stimulus.py and instead creates a virtual module to prevent issues if a collaborator doesn't have the stimuli repository.
3. FilterMethod has new 5Hz lowpass filter.

Add new Running methods and patch clocktools, shared

---

python/pipeline/odor.py
python/pipeline/utils/registration.py

StackMatching Update
* odor.StackMatching is a copy of stack.StackSet modified to only run on odor.MesoMatch scans with glomeruli
Registration Bug FIx
* stack.StackSet relies on registration.py's affine_product() function
* affine_product takes three tensors which are not checked for dtype and can fail if one tensor's dtype is float64 instead of float32
* This has been fixed by casting all tensors to dtype float64 before calculating the affine product

Adding odor.StackMatching and registration.py bugfix

---

python/pipeline/utils/copydata.py

copydata.py is a module used to transfer data from any two DataJoint servers, but has multiple specialized functions to copy data from the Tolias database to the Reimer database. It assumes schemas are shared between the two servers.

Added copydata to pipeline.utils

---

python/pipeline/utils/galvo_corrections.py

The original code overwrites `correct_raster` defined earlier and will throw "TypeError: <lambda>() takes 1 positional argument but 3 were given" for every scan that has a non-zero raster_phase.

fix: prevent overwriting function names in _get_correct_raster

---

python/pipeline/pupil.py

At some rigs (e.g. neuropixel recording rigs), there is no internal illumination from two-photon excitation, i.e., the pupil is black on gray background, thus a separate DeepLabCut model is required. 
This PR introduces a DeepLabCut model Alex and Maria helped train on neuropixel recordings. This model was able to reliably track the pupil in most scenarios as shown in the example recording session below. In the examples, the tracking and fitting results are shown below the raw frames. Red dots are tracking points and the yellow circle is the fitting result, the yellow circle will be absent if the tracking results do not pass a confidence threshold. 
This recording includes a wide range of pupil sizes, and the model reliably tracks the pupil's location and size.
This recording includes a …

add separate deeplabcut model for neuropixel recordings

---

python/pipeline/meso.py

The key_source function for meso.ScanInfo() is limited to only include two rigs: "2P4" and "R2P1". However, in order to run the LBM scans through the pipeline, we need to include a third rig: "V2P1" which corresponds to the Vizari Lab's LBM rig at Rockefeller where these initial LBM scans took place.
I have confirmed that this change will include Vizari LBM scans in meso.ScanInfo.key_source() by running an extracted key_source function in a notebook.

Add Vizari LBM machine to rig whitelist in meso.scanInfo.key_source()
